language: python
python:
    - "3.7"
sudo: required
services:
    - docker
dist: xenial
before_script:
    - docker build -t jorrvaskr:current .
    - docker-compose -f docker-compose-test.yml build
script:
    - sudo docker-compose -f docker-compose-test.yml run web
