version: '2.1'
services:
  db:
    image: "postgres:11.1-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jorrvaskr
    volumes:
      - pg_volume:/var/lib/postgresql/data
    healthcheck:
      test: su postgres -c 'psql -c "select 1"'
      interval: 1m
      timeout: 12s
      retries: 4
  web:
    build: .
    ports:
      - "16981:5000"
    volumes:
      - .:/jorrvaskr
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_volume:
